name: report
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches:
      - 8.x
jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
        env:
          STACK_VERSION: 8.16.0-SNAPSHOT
      - name: Build
        run: |
          cd report && bundle install
          echo "REPORT_DATE=`date "+%Y-%m-%d|%H:%M:%S"`" >> $GITHUB_ENV
      - name: Download Artifacts
        run: cd report && bundle exec rake download_all
      - name: Generate report
        run: cd report && bundle exec rake report
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: Updates API report ${{env.REPORT_DATE}}
          title: Updates API report
          author: 'Elastic Machine <elasticmachine@users.noreply.github.com>'
